source "https://supermarket.getchef.com"

cookbook 'apt', '~> 2.6.0'
cookbook 'apache2', '~> 2.0.0'
cookbook 'php', '~> 1.4.6'
cookbook 'mysql', '~> 5.5.2'
cookbook 'phpinfo', path: "/Users/cgerold/Desktop/Chef/chef-repo/cookbooks/phpinfo"